### ISSUE TITLE
support for major version incrementation

### ISSUE THREAD

**Issue by copejon** [roofmonkey/CI-UPSTREAM#3]
Lets decide how to do major version upgrades,,,, can this be automated via commit message? Or should we even worry about it at all?

(just some brainstorming...)
Right now

```
we explicitly grep for "ci-skip in commit message".
we always assume only the minor version is being incremented.
```

Lets make these key-value pairs sent into the bash script, example:

[ci-skip="false", version="auto"] translates to
--ci-skip=false --version=auto, which results in autoincrement of minor version along with auto publishing of the new version, that way someone who wants to upgrade the major version can do

commit -m "Lets bump to 2.2 [version="2.2.0"]

and then the version, rather than auto incrmented via python script, is explicitly set in the pom.

note , this is VERY low priority... because major releases are rarely implemented, and we have an easy workaround : Just turn build server off when we do a major release bump,do a pull request for the version bump, comment out the auto incrementer, and then manually run the build.

Then turn the CI back on and re-enable the auto-incrementer .

AFTER FURTHER BRAINSTORMING WITH JOHN, IM NOW OPEN TO CLOSING THIS ISSUE ENTIRELY. :)

**Comment by childsb** [comment]
this may be a total bust of the setup now and more difficult to implement, but what if we only build tags and master.

master = nightly builds,

tags = versioned builds.

so if i committed some changes, they would always show up in the 'nightly'/snapshot.

however if i tag code it builds that new tag and names the jar glusterfs-TAG.jar

then building either a major or minor release only a matter of tagging it..  of course to support the process of every commit = minor revision change, we'd have to tag after every commit (or change the process).
