### ISSUE TITLE
Deploy , test and evaluate new CI after merging pull 85

### ISSUE THREAD

**Issue by copejon** [roofmonkey/CI-UPSTREAM#6]
We need to evaluate the existing CI after releasing Pull #85.

1) Did it build and tests pass  -------------------Done
2) Did it run the mapreduce job ------------------Done
3) Did it autocommit and release the jar with incremented version to http://rhbd.s3.amazonaws.com/maven/indexV2.html  ------------------DONE!!!!

4) Are build/deploy scripts under version control somewhere (not necessarily on this repo)
5) Security : Have we audited security of the master build server/slave server

**Comment by copejon** [comment]
4) scripts moved into slave:/home/fedora/CI-UPSTREAM repository.  Jenkins job configs updated to reflect new paths
5) Jenkins server now requires usr acct before allowing user actions.  Users' privileges have been assigned; non-privileged users have only read access.

**Comment by jayunit100** [comment]
Great.... and now 6) Slave :  What sensitive files are on it and how can we protect them.

**Comment by copejon** [comment]
Conducting security audit with infosec right now to address any possible weaknesses
